### ISSUE TITLE
Keeps printing usage

### ISSUE THREAD

**Issue by KarmaMod** [CodingGay/BlackObfuscator#10]
No matter what i do, it keeps printing usage. What i'm doing wrong?

i'm using Windows 10

`./black-obfuscator -d 2 -i classes.dex -o classesout.dex`

**Comment by nnjun** [comment]
./black-obfuscator d2j-black-obfuscator -d 2 -i classes.dex -o classesout.dex

**Comment by KarmaMod** [comment]
it says `No classes found`

**Comment by nnjun** [comment]
see readme

**Comment by KarmaMod** [comment]
Ok, apparently i need to provide class, it does allow to obfuscate all. Now i got another error

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:698)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
        at org.jf.DexLib2Utils.saveDexFileDexLib2(DexLib2Utils.java:116)
        at org.jf.DexLib2Utils.splitDex(DexLib2Utils.java:79)
        at com.googlecode.dex2jar.tools.BlackObfuscatorCmd.doCommandLine(BlackObfuscatorCmd.java:103)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.dex2jar.tools.BlackObfuscatorCmd.main(BlackObfuscatorCmd.java:38)
```

**Comment by nnjun** [comment]
You can try downloading the source code and using idea

**Comment by developer-krushna** [comment]
> it says `No classes found`

Hey , how you fixed it can you help?
