### ISSUE TITLE
混淆工具报错

### ISSUE THREAD

**Issue by blueb0ne** [CodingGay/BlackObfuscator#14]
命令行方式进行混淆
`black-obfuscator.bat d2j-black-obfuscator -a filter.txt -d 2 -i classes.dex -o out.dex
`

错误如下
```java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:698)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
        at org.jf.DexLib2Utils.saveDexFileDexLib2(DexLib2Utils.java:116)
        at org.jf.DexLib2Utils.splitDex(DexLib2Utils.java:79)
        at com.googlecode.dex2jar.tools.BlackObfuscatorCmd.doCommandLine(BlackObfuscatorCmd.java:103)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
        at com.googlecode.dex2jar.tools.BlackObfuscatorCmd.main(BlackObfuscatorCmd.java:38)
```

**Comment by blueb0ne** [comment]
需要java 11环境
