### ISSUE TITLE
java.lang.VerifyError: Verifier rejected class

### ISSUE THREAD

**Issue by google-mirror** [CodingGay/BlackObfuscator#24]
```
         07-12 15:28:10.285  3403  3403 D AndroidRuntime: Shutting down VM
         07-12 15:28:10.285  3403  3403 E AndroidRuntime: FATAL EXCEPTION: main
         07-12 15:28:10.285  3403  3403 E AndroidRuntime: Process: a.test, PID: 3403
         07-12 15:28:10.285  3403  3403 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class a.Application: void a.Application.onCreate() failed to verify: void a.Application.onCreate(): [0x13A] register v1 has type Precise Reference: java.lang.Object but expected Precise Reference: a.c6 (declaration of 'a.Application' appears in /data/app/~~6puBK70S29XrnAqbfVRxzA==/a.test-wsJuVdj9tNZlY3SMzEdSTg==/base.apk)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1189)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1377)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7059)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.app.ActivityThread.access$1700(ActivityThread.java:277)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2170)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:211)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:300)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8285)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
         07-12 15:28:10.285  3403  3403 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
```

**Comment by google-mirror** [comment]
"-d", "2"
